Create tables on startup rather than on first request
Otherwise we get problems running the tests for the first time and
calling `reset_db()`, as the table is present in the metadata but not
actually present in the DB. This causes issues like:

ProgrammingError: (ProgrammingError) relation "service_to_service_access_token" does not exist
LINE 1: delete from "service_to_service_access_token"
                    ^
 'delete from "service_to_service_access_token"' {}